Develope/config
ASeegull/edriver-space pull request #8
Opened 2021-11-25 12:18 UTC by skskuzan

Pushing config to main branch

2021-11-25 17:07 UTC, AlexMykhailov1 requested changes, later dismissed
Already discussed in the chat.

2021-11-27 18:19 UTC, skskuzan reviewed
ready

2021-11-28 11:41 UTC, AlexMykhailov1 approved these changes

2021-11-28 13:08 UTC, mariareshetovska approved these changes

2021-11-28 13:50 UTC, merged